name: reloj
description: Aplicación Wear OS para TOPY, enfocada en salud y bienestar.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5  # Iconos adicionales
  #fl_chart: ^0.36.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1  # Buenas prácticas de código

flutter:
  uses-material-design: true

  assets:
    - assets/images/file.png
    - assets/images/
